### ISSUE TITLE
Update services list to include all of CU services

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#108]
Here's the full list: https://drive.google.com/open?id=1OgZf5acOTpbd-O0Up8ItRlW81Vspq8Rc6yrES1JlwLk

Here's the list we currently are using: https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/migrations/sqls/20190512164549-services-list-up.sql#L7-L20

**Comment by MeghanBomberger** [comment]
The services in https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/migrations/sqls/20190512164549-services-list-up.sql#L7-L20 match those on the intake form (https://docs.google.com/document/d/11xR81Apviro11sIbuMN9fZpGHd4_yt8MoHxLMnkaYeI/edit). Do we need a second list of services to differentiate between all the individual services they have available and the summary description of types of services in each program the clients check on the intake?

**Comment by joeldenning** [comment]
The problem is that the list in the intake form on page 1 is different from the list on page 2 and 3.

**Comment by joeldenning** [comment]
Done as part of client interactions.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/5524384/64069264-52f0ed00-cc03-11e9-95c5-aeabded3dfcd.png">
