### ISSUE TITLE
Add easy way to clear the client list search box.

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#124]
Maybe an X inside of the text input, on the far right?

<img width="874" alt="image" src="https://user-images.githubusercontent.com/5524384/59008537-fc346c80-87e7-11e9-8a25-2024197a9599.png">

**Comment by MeghanBomberger** [comment]
Is not clearing the input when search button is clicked intentional?

**Comment by joeldenning** [comment]
Yes it is intentional -- so that you can modify your search without having to type it all in again. Also, it is intentional that when you refresh the page, the search is still there.

**Comment by joeldenning** [comment]
Resolved with #130
