### ISSUE TITLE
Created date in Client List is wrong

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#139]
I think it might be showing today's date for all clients as the created date. See screenshot below:

<img width="1277" alt="Screen Shot 2019-06-19 at 11 19 30 PM" src="https://user-images.githubusercontent.com/5524384/59797721-1773a180-92e9-11e9-87ed-f7a3e2096945.png">

**Comment by MeghanBomberger** [comment]
Is this the dateOfIntake date?

**Comment by joeldenning** [comment]
No it's `client.dateAdded`. https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/frontend/client-list/table/desktop-clients-table.component.tsx#L93

Not sure if it's the frontend or backend causing them all to render as the same date.

**Comment by MeghanBomberger** [comment]
Any  chance the validator could be resetting it?

https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/73cef6b85d3c14f160f571fe3e74dd1ba9e92298/backend/apis/utils/validation-utils.js#L63

**Comment by joeldenning** [comment]
I don't think so, no. In javascript, there is no way to modify a string -- only create new strings. And the validator isn't creating a new string but just returning `null` when there is no validation issue and `Property ${propertyName} must be a string date of format YYYY-MM-DD. Received '${val}'` when it is a validation issue.
