### ISSUE TITLE
Update add client to match latest copy of intake form

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#171]
https://docs.google.com/document/d/11xR81Apviro11sIbuMN9fZpGHd4_yt8MoHxLMnkaYeI/edit

**Comment by joeldenning** [comment]
Not sure what this is referring to. Can you clarify, @MeghanBomberger ?

**Comment by MeghanBomberger** [comment]
I think I may have mixed up which version was the latest. I was comparing the one linked above to this one: https://docs.google.com/document/d/1plhLc6B2yeXL10VAeu_SB-4UyZ-wywPy0RHRWCPFs0s/edit and saw a bunch of differences.
