### ISSUE TITLE
Add some visual separation to the client history

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#174]
Line, border, or background color matching the dot color. Just something to more easily identify where the breaks are. 

Dot also lining up to the top instead of middle maybe?

**Comment by joeldenning** [comment]
Done as part of client interactions:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5524384/64069164-74e97000-cc01-11e9-8257-3b873a5c209f.png">
