### ISSUE TITLE
CU pate is not working

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#200]
From: Fernando, fernando@cuutah.org

Information about error: 

{
    "error": "Failed to execute 'pushState' on 'History': Error: Api request to '/api/clients?page' failed with HTTP status 504 could not be cloned.\nError: Failed to execute 'pushState' on 'History': Error: Api request to '/api/clients?page' failed with HTTP status 504 could not be cloned.\n    at ui (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:38:132680)\n    at Object.action (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:38:134579)\n    at https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:38:133842\n    at onClick (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:38:133852)\n    at Object.<anonymous> (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:879)\n    at f (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:917)\n    at https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:1555\n    at C (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:1644)\n    at N (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:2080)\n    at O (https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js:29:1892)",
    "message": "Uncaught DataCloneError: Failed to execute 'pushState' on 'History': Error: Api request to '/api/clients?page' failed with HTTP status 504 could not be cloned.",
    "filename": "https://database.cuutah.org/static/comunidades-unidas-internal.9b52bc156d8638528f8d.js",
    "lineno": 29,
    "colno": 3000
}

**Comment by joeldenning** [comment]
I broke prod with a failed db migration. It is now fixed.
