### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#208]
From: Fernando, fernando@cuutah.org

Information about error: 

{
    "error": "Failed to execute 'pushState' on 'History': DOMException object could not be cloned.\nError: Failed to execute 'pushState' on 'History': DOMException object could not be cloned.\n    at si (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:38:132814)\n    at Object.action (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:38:134713)\n    at https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:38:133976\n    at onClick (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:38:133986)\n    at Object.<anonymous> (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:879)\n    at f (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:917)\n    at https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:1555\n    at C (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:1644)\n    at N (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:2080)\n    at O (https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js:29:1892)",
    "message": "Uncaught DataCloneError: Failed to execute 'pushState' on 'History': DOMException object could not be cloned.",
    "filename": "https://database.cuutah.org/static/comunidades-unidas-internal.25829d958e68a5ac7e1f.js",
    "lineno": 29,
    "colno": 3000
}

**Comment by joeldenning** [comment]
Fixed in https://github.com/JustUtahCoders/comunidades-unidas-internal/commit/d69ff8797c43fbb391ab8a3a34804942d1704716
