### ISSUE TITLE
Datos Actuales

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#210]
From: Mirna carrera, no@nonononono

es Casada
No trabaja
Pais de Origen : Mexico
Llego a EEUU : Octubre 2004

**Comment by joeldenning** [comment]
I think I understand the spanish but I don't understand what this message means. Also there's no email address to contact Mirna at so I emailed Vicky to see if she can shed some light on it.

**Comment by joeldenning** [comment]
Closing this because I haven't heard from Vicky about it.
