### ISSUE TITLE
Client Interactions deleted and updated items

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#230]
When deleting a client interaction the original is still on the log list with no info inside and no indication if it was the one that was deleted. We should add a visual to indicate which are delete if they are staying in the log in addition to the logging of the deletion, or they should be removed in place of the deletion log. Same with updated. It should replace the original and indicate it was updated and when or the original needs some indicator that it is not the current copy (font color or strike through with a note of see logid # to connect them maybe?)

**Comment by joeldenning** [comment]
Screen shot / gif?

The behavior you're describing is not what I see.
