### ISSUE TITLE
Make income optional in client intake

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#237]
Make date of arrival optional, too

**Comment by MeghanBomberger** [comment]
NOTE: on hold until verifying with Vicky we still need this added.

**Comment by joeldenning** [comment]
Verdict: date of arrival optional, household income not.

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/5524384/66101356-c58b1a80-e56b-11e9-802d-793063abc664.png">
