### ISSUE TITLE
Remove Youth Groups from Preventive Health Program

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#262]
Youth Groups / Leadership Development should not be in Preventive Health. It already exists under Community Engagement and Organizing.

**Comment by MeghanBomberger** [comment]
This has been removed from PR #273 and will be readdressed in a new PR due to the conflicts we were running into.

**Comment by joeldenning** [comment]
@dvnrsn is maybe going to look on this

**Comment by joeldenning** [comment]
Done
