### ISSUE TITLE
Add missing down migrations

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#268]
https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/migrations/sqls/20190508233238-clients-down.sql

https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/migrations/sqls/20190512164549-services-list-down.sql

https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/migrations/sqls/20190607164137-clear-test-data-down.sql

**Comment by joeldenning** [comment]
Good enough I think
