### ISSUE TITLE
create leads front end

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#310]
MVP:
* ability to add multiple leads at once to improve data entry speed
* ability to add the relevant event or select from an already added event

Would Be Nice:
* Confirmation page similar to the create a client but showing a table of the leads (mimic the paper copy somewhat)
* "kiosk mode" that lets the staff member select/start the event and then feeds into a single lead form so that attendees can type in their own info without seeing others info and without having to select the even themselves

**Comment by joeldenning** [comment]
Done
