### ISSUE TITLE
Printing client list

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#376]

**Comment by MeghanBomberger** [comment]
What info will be needed on the printed version? Same as the client list in system or other?

**Comment by joeldenning** [comment]
All the we need to do for this is add a [`@media print`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#examples) css rule that hides the sidebar and page header. Then we need to ensure that rows on the client list can fit in a portrait 8.5x11 page.
