### ISSUE TITLE
Print out human readable date underneath date pickers

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#39]
To avoid confusion

**Comment by joeldenning** [comment]
To do this, we'd create a `date-input.component.tsx` that would have the following:

```tsx
<input type="date" />
<div>{dateformat(date, "m/d/yyyy")}</div>
```

And then  replace all of our date components with it.

**Comment by MeghanBomberger** [comment]
Was this resolves with one of the previous date fixes?

**Comment by joeldenning** [comment]
No it was not. I actually think that this one is probably unnecessary -- we can just rely on browser's `<input type="date">` to have a good enough UX for people to understand.

Closing
