### ISSUE TITLE
Duda en fecha de nacimiento

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#395]
From: Dora Nunez, dora@cuutah.org

Hola Joel , buenos dias , estoy metiendo a database , y no me deja poner la fecha de nacimiento del cliente.

**Comment by joeldenning** [comment]
I emailed Dora asking for more information. I didn't immediately see anything wrong with the birthday field when adding a client.

![Nov-20-2019 15-02-17](https://user-images.githubusercontent.com/5524384/69282325-4303fc00-0ba7-11ea-96c8-f40d0263141f.gif)

**Comment by joeldenning** [comment]
From Dora:

> Sorry , Joel mi computadora era la que estaba mal, mil disculpas de tanta molestia , ustedes están haciendo un buen trabajo , gracias por todo lo que hacen.
