### ISSUE TITLE
Can't go pass first page

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#41]
From: Luis Garza, luis@cuutah.org

Joel,

The system is not allowing us to go after the initial page "Check if the person is already in the system." The staff has not been able to test the system. 

Let us know. Gracias!

**Comment by joeldenning** [comment]
This is the one I mentioned in our last meeting. It's not working because the check duplicates API isn't working, since I removed some of the database tables in that big PR so that I could merge the PR without having to make sure all the tables were right.

I'll look into this today

**Comment by joeldenning** [comment]
This is now fixed
