### ISSUE TITLE
referrals to mammograms 

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#416]
From: yehemy, yehemy@cuutah.org

Hello all,

We just received new funding for Mammograms to the State Health Department and I wanted to ask you if it is possible to add a section in clients when we do referrals to link it to the name of the referral or the type of referral we are doing. I know it could take a lot of time to do this, and we can be patience, Is it possible?

**Comment by joeldenning** [comment]
I replied to Yehemy about this today.

**Comment by joeldenning** [comment]
Implemented
