### ISSUE TITLE
Make Add Client handle going back and forth through different steps

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#50]
State should not be lost as the user goes between steps, backwards or fowards.

**Comment by MeghanBomberger** [comment]
Could holding the info in local storage and then clearing it from local storage once submitted solve this?

**Comment by joeldenning** [comment]
No, we can just use the `clientState` to hold it, since that state isn't recreated/destroyed as you navigate between steps
