### ISSUE TITLE
adding a new client

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#531]
From: vicky fuentes, vicky@cuutah.org

Information about error: 

{
    "error": "Unexpected token <\nSyntaxError: Unexpected token <",
    "message": "Uncaught SyntaxError: Unexpected token <",
    "filename": "https://database.cuutah.org/static/0.be5732b1ec97faf57b81.js",
    "lineno": 1,
    "colno": 1
}

**Comment by joeldenning** [comment]
Closing this in favor of the more descriptive https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/532

**Comment by joeldenning** [comment]
Emailed vicky about this, too
