### ISSUE TITLE
Phone inputs should allow hyphens and parentheses

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#562]
See related https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/561. Vero confirmed it was the hyphens

**Comment by joeldenning** [comment]
This includes when adding and updating both clients and leads.

**Comment by leahjlou** [comment]
Could not reproduce for adding/editing clients or leads. Parens and hyphens were all OK. Closing this.
