### ISSUE TITLE
Add date range for english level, country, client source, age and gender reports

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#582]
The date represents the date of intake

**Comment by joeldenning** [comment]
Here is where you can see those reports. We should add date range inputs to them.

http://localhost:8080/reports/english-levels

http://localhost:8080/reports/countries-of-origin

http://localhost:8080/reports/client-sources

http://localhost:8080/reports/ages-and-genders

Here is an example of a report that does a date range: http://localhost:8080/reports/interaction-hours-by-client?maxInclusive=false&minInclusive=false

**Comment by HappyViki** [comment]
@joeldenning `ages-and-genders` has a clients and leads list. From what I understand only clients have date of intake. I'm not sure how to display results. I feel it might be confusing if clients are being filtered based on certain date and leads are not.

I think one solution to make it less confusing is to pick leads from a certain date range as well, except it would be date of sign up.

What do you think?

**Comment by joeldenning** [comment]
Good question - for leads we can use the `dateOfSignUp` column:

https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/652e9b479dbb345e92d25f912fef6cd299c282e4/migrations/sqls/20191002015049-leads-and-events-up.sql#L17

**Comment by joeldenning** [comment]
This is done
