### ISSUE TITLE
New client error

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#594]
From: Kimberly, kimberly@cuutah.org

Information about error: 

{
    "error": null,
    "message": "Script error.",
    "filename": "",
    "lineno": 0,
    "colno": 0
}

I try to add a new client and it says there is an error and won't let me proceed. It also comes up when I want to make someone that is a lead into a client.

**Comment by joeldenning** [comment]
I believe this was caused by putting in invalid email addresses, such as `name@hotmail` instead of `name@hotmail.com`.
