### ISSUE TITLE
Mensajes de texto

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#625]
From: Dora Nunez, dora@cuutah.org

 Hoal Joel tengouna pregunta ,Se mando un mensaje de texto a todos los clientes y salio error

**Comment by joeldenning** [comment]
I sent her an email about this - I think it was caused simply by browser timeout. The logs show that it took 8 seconds to send the text messages, but that the http response status was 200

> POST /api/bulk-texts?page=1&sortField=lastName&sortOrder=asc 200 153 - 8320.231 ms Tue Sep 01 2020 23:17:16 GMT+0000 (Coordinated Universal Time)
