### ISSUE TITLE
When viewing event, show list of leads from that event.

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#684]

**Comment by joeldenning** [comment]
This is what viewing an Event currently looks like. We want to add a new card to it that shows the leads that were created from that event:

![image](https://user-images.githubusercontent.com/5524384/99114377-f41c5700-25ad-11eb-8459-aab23a7b0230.png)

To view an event, click on Event List in the sidebar then click on an event. To create an event, go to Add Leads and create an event there.

Backend work:

In [this file](https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/backend/apis/events/get-event.api.js), we are already retrieving the list of lead ids associated with an event. However, we're not retrieving the lead name. So we need to join with the leads table to get the lead names. Then we need to send an array of lead objects in the API response. The [api documentation for getting an event](https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/api-docs/events.md) should be updated accordingly.

Frontend work:

The [EventHome component](https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/frontend/view-edit-events/event-home/event-home.component.tsx) is what shows an event. We should add a new child component EventLeads that is a new card that shows a table of the leads. Each row should have the lead id and lead name. The lead id should be a link to `/leads/:leadId`. You can use the BasicTableReport component to show the table.

**Comment by TheMcMurder** [comment]
I'll work on this one today.
