### ISSUE TITLE
Questions about data for reports

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#768]
From: marifer, marifer@cuutah.org

Hello Joel, 

I wanted to know if it was possible to export the data from an advanced search list. 

We are trying to contact clients we have for a specific program but we are looking at over 300 clients that we will need to contact. Clicking their account one by one would take too long. I was wondering if I do the advance search, get the list and be able to export it with name, phone number and address to then work off it as a list rather than click each client account, get the info, go back to the search and work that way. 

Thank you,

**Comment by nick-nack-attack** [comment]
I've started working on this.

**Comment by joeldenning** [comment]
I'll email marifer to see what format she'd want the export in. Maybe CSV? Not sure. It's possible they'd want to just print the list, too, so it's probably best to hold off on writing any code until we understand what the feature is.

**Comment by joeldenning** [comment]
Here's the email I sent:

>>>
> Hi Marifer,
> 
> I saw the issue you created at https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/768 regarding exporting report data.
> 
> We're happy to work on this feature, but want to make sure we understand it correctly, first. How would you like the export to work? Would it download a CSV file that you can open in Excel? Or would it do something else?
> 
> Thanks,
> Joel

**Comment by joeldenning** [comment]
Here was her response:

> Hi Joel, 
> 
> Thank you so much, and yes that would be great in that format to open in excel or google spreadsheets (i think it supports the CSV format). 
> 
> Would that be possible?

I said that we'd do that. I think that we could probably do this all on the frontend side, but am open to doing it on the backend, too. If you want to work on it, @nick-nack-attack, feel free to. Otherwise I'll work on it at some point.

**Comment by nick-nack-attack** [comment]
@joeldenning right I was working on doing a csv export with the clients that are selected. Though she wants address included and it's not in the data in the Clients list. So I was joining to collect the user ids, put it into an array, and query the api to return name, phone, and address.

**Comment by nick-nack-attack** [comment]
@joeldenning I can do it but if someone else is down to do the new endpoint, that'd be cool. Otherwise, everything is ready on the frontend.

**Comment by nick-nack-attack** [comment]
@joeldenning check out #770 for my latest work (draft branch).
