### ISSUE TITLE
Duplicates when running report by # of hrs

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#788]
From: Marifer, marifer@cuutah.org

Hi again Joel, I forgot to mention that we are running into an issue when we run the report by hour (especifically running it for minimum of 6 with no maximum), it is showing duplicates for certain clients. It shows their name multiple times with the same number of hours but I'm not sure why it's happening. I ran it from November 2020 to now and 3 people showed up duplicated Wendy Cordova, Cecilia Figueroa and Ketty Rojas. I checked their interactions to make sure they weren't added like 3 times for the same number of hours but they weren't. Do you think it's just an issue with the report? Thank you again for all your help!

**Comment by joeldenning** [comment]
Emailed her about htis - we should fix it.
