### ISSUE TITLE
email

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#802]
From: Dora Nunez, dora@cuutah.org

Hola Joel.
  Espero y estes bien aqui estoy otra vez dando lata, sabes que no me salen la lista de clientes, por mas que le muevo no me salen , voy a mandar un mensage de texto a los clientes de Database y no me sale ninguno, sabes porque sera, o yo estare mal y lo pongo mal .
estare  atenta a cualquier cosa gracia por todo.

**Comment by joeldenning** [comment]
emailed her about this
