### ISSUE TITLE
Referencias uno a uno

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#805]
From: ROCIO CAMPOS, rocio@cuutah.org

Hola Joel me gustaría saber si podríamos tener la posibilidad de tener la opción de referencias 101 porque hay muchas personas a las que se les da la referencia en eventos donde la gente nos pide recursos pero no nos dan la información completa. Espero tu respuesta gracias.
Yo tengo mi lista de referencias asi y me gustaria que estuvieran en Data base.

https://docs.google.com/spreadsheets/d/16zOMb4ar-RYAr2PJqhAXuB7bb0YgwsP69xmqtm5W9G4/edit?usp=sharing

**Comment by joeldenning** [comment]
Emailed her and Yehemy about this
