### ISSUE TITLE
intake

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#812]
From: Dyandy Herrera, dyandy@cuutah.org

Information about error: No se porque no me permite guardar este intake, ya lo intente dos veces el dia de hoy

{
    "error": null,
    "message": "Script error.",
    "filename": "",
    "lineno": 0,
    "colno": 0
}

**Comment by joeldenning** [comment]
Unfortunatley no information
