### ISSUE TITLE
email

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#823]
From: Dora Nunez, dora@cuutah.org

Hola Joel.
Espero que estes muy bien, joel cuendo busco un cliente , pongo el nombre y el # de cliente y no sale ningun nombre , ni poniendo el apeido, tengo que hacer como que lleno otra vez el intake, y ahi es cuando sale si esta duplicado oh no, y es como lo lo estoy haciendo asi estoy buscando el cliente para poner la interaccion, ya tengo toda la semana , con ese problema, soory que nomas te contactamos para eso , que tengas bonito dia y fin de semana.

**Comment by joeldenning** [comment]
She also emailed about this, I will respond there
