### ISSUE TITLE
make intake

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#825]
From: Valeria, Valeria@cuutah.org

Information about error: 

{cuando termino de poner toda la información de la persona y le pongo continuar me sale que hay un error y no me deja completar el intake
    "error": null,
    "message": "Script error.",
    "filename": "",
    "lineno": 0,
    "colno": 0
}

**Comment by joeldenning** [comment]
don't know how to debug this
