### ISSUE TITLE
No me permite ver toda la informacion del cliente, ni me deja convertir leads en clientes o solo agregar clientes, estoy atenta a sus comentarios

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#841]
From: Dyandy Herrera, dyandy@cuutah.org

Information about error: 

{
    "error": null,
    "message": "Script error.",
    "filename": "",
    "lineno": 0,
    "colno": 0
}

**Comment by joeldenning** [comment]
Emailed her
