### ISSUE TITLE
Database might be returning dateAdded timestamps in wrong time zone

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#92]

**Comment by MeghanBomberger** [comment]
What's the timezone offset its currently returning?

**Comment by joeldenning** [comment]
It's returning UTC. Example: `2019-05-31T11:09:24.000Z`. And then javascript date objects in the browser convert those to MDT which are behind UTC.

**Comment by MeghanBomberger** [comment]
Was this resolved with the backend date we merged with the overall date PR?

**Comment by joeldenning** [comment]
This is the bug that was magically fixed without us doing anything to the code. The "last updated" dates in the client page was showing the wrong dates. But then started showing the right dates.

I guess we'll close until we can reproduce it or see this again.
